@base_url = https://my-json-server.typicode.com/augustocesarfmo/crud-rest-web

// Listando os registros
GET {{base_url}}/products

###

// Recuperando um registro específico
GET {{base_url}}/products/1

###

// Criando um novo registro
POST {{base_url}}:3000/products
content-type: application/json

{
  "nome": "Melancia"
}

###

// Atualizando um registro
PUT {{base_url}}/products/173
content-type: application/json

{
  "nome": "Recife/PE"
}

###

// Deletando um registro
DELETE {{base_url}}/products/172